{
 "title": " MySQL – Write Path",
 "panels": [
  { "title": "MySQL Write Path", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Throughput DML/sec",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "rate(mysql_global_status_commands_total{command=\"insert\"}[1m])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(mysql_global_status_commands_total{command=\"update\"}[1m])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(mysql_global_status_commands_total{command=\"delete\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Commit Rate (TPS)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 1 },
   "targets": [
    {
     "expr": "sum(\r\n  rate(mysql_global_status_commands_total{command=~\"commit|rollback\"}[1m])\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "fsyncs/sec (InnoDB log sync pressure)",
   "type": "timeseries",
   "description": "baixo e estável → ok\ncrescendo proporcional ao TPS → normal\nalto demais com TPS baixo → flush excessivo / innodb_flush_log_at_trx_commit",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "rate(mysql_global_status_innodb_os_log_fsyncs[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current configs",
   "type": "table",
   "gridPos": { "h": 18, "w": 6, "x": 18, "y": 1 },
   "targets": [
    {
     "expr": "last_over_time(mysql_global_variables_autocommit[5m])",
     "legendFormat": "autocommit"
    },
    {
     "expr": "last_over_time(mysql_global_variables_binlog_group_commit_sync_delay[5m])",
     "legendFormat": "binlog_group_commit_sync_delay"
    },
    {
     "expr": "last_over_time(mysql_global_variables_binlog_order_commits[5m])",
     "legendFormat": "binlog_order_commits"
    },
    {
     "expr": "last_over_time(mysql_global_variables_innodb_commit_concurrency[5m])",
     "legendFormat": "innodb_commit_concurrency"
    },
    {
     "expr": "last_over_time(mysql_global_variables_innodb_flush_log_at_trx_commit[5m])",
     "legendFormat": "innodb_flush_log_at_trx_commit"
    },
    {
     "expr": "last_over_time(mysql_global_variables_sync_binlog[5m])",
     "legendFormat": "sync_binlog"
    }
   ]
  },
  {
   "title": " fsyncs vs commits",
   "type": "timeseries",
   "description": " Leitura:\n\n≈ 1 → commit síncrono (fsync a cada commit)\n< 1 → group commit funcionando\n>> 1 → flush extra / problema sério",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "rate(mysql_global_status_innodb_os_log_fsyncs[1m])\r\n/\r\nclamp_min(\r\n  rate(mysql_global_status_commands_total{command=\"commit\"}[1m]),\r\n  1\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Commit cost (fsync pressure)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 11 },
   "targets": [
    {
     "expr": "rate(mysql_global_status_innodb_os_log_written[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Write pressure total - innodb_data_written",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 11 },
   "targets": [
    {
     "expr": "rate(mysql_global_status_innodb_data_written[1m])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}