services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: unless-stopped
    command:
      - --innodb-redo-log-capacity=4G
      - --innodb_flush_log_at_trx_commit=1
      - --sync_binlog=1

    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: appdb
      MYSQL_USER: appuser
      MYSQL_PASSWORD: apppass
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
    networks:
      - monitoring


  mysqld_exporter:
    image: prom/mysqld-exporter
    container_name: mysqld_exporter
    restart: unless-stopped
    volumes:
      - ./mysqld-exporter/.my.cnf:/etc/.my.cnf:ro
    command:
      - "--config.my-cnf=/etc/.my.cnf"
    depends_on:
      - mysql
    ports:
      - "9104:9104"
    networks:
      - monitoring


  prometheus:
    image: prom/prometheus
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - monitoring

  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: unless-stopped
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
    volumes:
      - ./data/grafana:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    networks:
      - monitoring

  sysbench:
    image: severalnines/sysbench
    container_name: sysbench
    profiles:
      - bench
    volumes:
      - ./sysbench:/work
    entrypoint: ["sleep", "infinity"]
    depends_on:
      - mysql
    networks:
      - monitoring

networks:
  monitoring:
    driver: bridge
